services:
  rekkoo-server-api:
    build:
      target: development
    command: npm run dev
    environment:
      - AI_SERVER_URL_LOCAL=http://ai-server:8000
      - AI_SERVER_URL_REMOTE=https://ai.rekkoo.com
      - AI_SERVER_ENV=local
      - VALKEY_URL=redis://valkey:6379
    env_file:
      - .env.common
      - .env.development
    volumes:
      - ./src:/app/src
      # Do NOT mount /app/node_modules
      # Optionally mount other files if needed:
      # - ./config:/app/config
      # - ./.env.development:/app/.env.development
    extra_hosts:
      - "ai-dev.rekkoo.com:172.18.0.6"  # AI server's actual IP in the proxy network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # HTTP router for api-dev.rekkoo.com
      - "traefik.http.routers.rekkoo-server-api-http.rule=Host(`api-dev.rekkoo.com`)"
      - "traefik.http.routers.rekkoo-server-api-http.entrypoints=web"
      - "traefik.http.routers.rekkoo-server-api-http.service=rekkoo-server-api"
      # HTTPS router for api-dev.rekkoo.com
      - "traefik.http.routers.rekkoo-server-api-https.rule=Host(`api-dev.rekkoo.com`)"
      - "traefik.http.routers.rekkoo-server-api-https.entrypoints=websecure"
      - "traefik.http.routers.rekkoo-server-api-https.tls=true"
      - "traefik.http.routers.rekkoo-server-api-https.service=rekkoo-server-api"
      # Service definition
      - "traefik.http.services.rekkoo-server-api.loadbalancer.server.port=3100"

  valkey:
    container_name: rekkoo-valkey-dev
    labels:
      - "traefik.enable=false"  # Don't expose via Traefik
    ports:
      - "6379:6379"  # TEMPORARY: For GUI access - remove when done
    # No external ports - accessible via docker exec if debugging needed