services:
  rekkoo-server-api:
    build:
      target: development
    command: npm run dev
    environment:
      - AI_SERVER_URL_LOCAL=http://ai-server:8000
      - AI_SERVER_URL_REMOTE=https://ai.rekkoo.com
      - AI_SERVER_ENV=local
    env_file:
      - .env
      - .env.development
    volumes:
      - ./src:/app/src
      - /app/node_modules
    extra_hosts:
      - "ai-dev.rekkoo.com:172.18.0.6"  # AI server's actual IP in the proxy network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.rekkoo-server-api.rule=Host(`api.rekkoo.local`) || Host(`api-dev.rekkoo.com`)"
      - "traefik.http.routers.rekkoo-server-api.entrypoints=web"
      - "traefik.http.services.rekkoo-server-api.loadbalancer.server.port=3100"
