services:
  rekkoo-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rekkoo-server
    restart: unless-stopped
    networks:
      - proxy
    env_file:
      - .env.common

networks:
  proxy:
    external: true
