services:
  rekkoo-server-api:
    build:
      target: development
    command: npm run dev
    environment:
      - AI_SERVER_URL_LOCAL=http://ai-server:8000
      - AI_SERVER_URL_REMOTE=https://ai.rekkoo.com
      - AI_SERVER_ENV=local
    env_file:
      - .env.common
      - .env.development
    volumes:
      - ./src:/app/src
      # Do NOT mount /app/node_modules
      # Optionally mount other files if needed:
      # - ./config:/app/config
      # - ./.env.development:/app/.env.development
    extra_hosts:
      - "ai-dev.rekkoo.com:172.18.0.6"  # AI server's actual IP in the proxy network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.rekkoo-server-api.rule=Host(`api-dev.rekkoo.com`)"
      - "traefik.http.routers.rekkoo-server-api.entrypoints=web"
      - "traefik.http.services.rekkoo-server-api.loadbalancer.server.port=3100"